###

GET http://localhost:3000

###

GET http://localhost:3000/post

###

GET http://localhost:3000/post?sender=123456

###

GET http://localhost:3000/post/635e7e7b45c51a54945675be

###

POST  http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "user1@gmail.com",
    "password": "12345"
}

###

POST  http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "user1@gmail.com",
    "password": "12345"
}

###
